### ISSUE TITLE
Cannot get Business shared Folders

### ISSUE THREAD

**Issue by raffaem** [bpozdena/OneDriveGUI#100]
I shared a folder from one of my OneDrive account to another OneDrive account of mine.

I added the latter as "Direct access".

I guess it counts as "Business Shared Folder"?

However the GUI shows no business shared folders:

![image](https://user-images.githubusercontent.com/54762742/232821425-becce42e-b411-4d81-aca3-3702e857325f.png)

From the folder account I am able to visualize folders others have shared with me.

But I can't visualize this folder I shared with myself from the latter account.

**Comment by bpozdena** [comment]
Unfortunately, business shared folders, as the name suggests, are only supported between accounts from the same business/organization. 

This limitation is documented in the [client's documentation](https://github.com/abraunegg/onedrive/blob/master/docs/BusinessSharedFolders.md#known-issues). 

Since you have access to both accounts, you can simply create two OneDrive profiles in the GUI and sync both of them.

**Comment by raffaem** [comment]
I see.

I'm going to lose access to one of those accounts. That's the point of it.

How can I sync folders shared form another organization?

Because I can see the folder under "Shared folder" in the web interface, but i cannot see it in my file system.

**Comment by bpozdena** [comment]
Check the previously liked documentation for answers.
