### ISSUE TITLE
Browser Selection for Login

### ISSUE THREAD

**Issue by erenoglu** [bpozdena/OneDriveGUI#123]
Thanks for this great GUI! Works great! I have one request, our corporate enforces policy with use of Intune and the use of microsoft-edge for corporate resources, including logging in, enforced by intune. It seems onedrivegui uses default browser or some other browser window to try to login, which gets rejected. Is it possible to have a setting to point to a binary for login browser selection? That way I could point it to microsoft-edge which would login normally and give the return.

**Comment by bpozdena** [comment]
I've been slowly deprecating the built-in browser because of various dependency issues on some distributions. 

So I'm now forcing users to login via their external browsers by clicking on a simple hyperlink. You will therefore need to change your default browser to influence where the link will open. It's the same as clicking on a link in any other app like Thunderbird etc.

It'll probably make more sense to change your default browser to affect link behaviour in all apps. But you can try to change my mind.

**Comment by erenoglu** [comment]
Thanks, I'm on Arch and package was built from Aur. This was not the behavior. I was presented a login window (probably internal) which ultimately didn't work as it wasn't Edge.

**Comment by erenoglu** [comment]
I mean, should I have used the "git" version of AUR package (I'm using the 1.0.3 package) to get the external auth prompt? Or the Appimage?

**Comment by bpozdena** [comment]
Appimage will always use the external login via browser. 

Since you're running the source code directly, you'll need to modify the bellow line 
https://github.com/bpozdena/OneDriveGUI/blob/92d18f1fb33b33b8cf44962fd272979dc596aeb9/src/OneDriveGUI.py#L61

To:
'APPIMAGE = True'

**Comment by erenoglu** [comment]
Thanks, did the change, will try in the next time it asks for login refresh.

**Comment by bpozdena** [comment]
OK, thanks for the confirmation. I will disable the buit-in browser permanently in the next release.
