### ISSUE TITLE
Allow forcefully bypassing resync on configuration modification.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bpozdena/OneDriveGUI#142]
In order to provide a means of bypassing issues like https://github.com/bpozdena/OneDriveGUI/issues/141#issue-2001196335.

**Comment by abraunegg** [comment]
@RokeJulianLockhart 
A resync is required to ensure the local state is correct based on *your* client side filtering operation rules.

It should not be bypassed.

> I have almost 1 TiB of content to synchronize, and have downloaded an awful lot already, so this simply isn't feasible.

'onedrive' client version v2.4.x will be *really* slow .. due to how the original was coded. v2.5.x has been 100% re-written and dramatically improves sync activities. I would advise you to use v2.5.x given the maturity of the code with logging output for large file transfers being the main outstanding issue to complete (which is in progress).

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpozdena/OneDriveGUI/issues/142#issuecomment-1821569172

@abraunegg, I shall the moment it hits https://software.opensuse.org/download/package?package=onedrive&project=openSUSE%3AFactory#directopenSUSE because I really want the dependency management and integration my distribution package provides. Thanks lots though.

**Comment by bpozdena** [comment]
Closing as the full re-sync is required by the client after a configuration change is made. 

Note that full re-sync does not mean that all data will be re-transmitted. It only means that the local sync state of all files will be removed and the client therefore needs to check every single file to see if it was modified/removed. At least that is my understanding. In any case, as advised by abraunegg, the process is significantly faster in onedrive client v2.5.
