### ISSUE TITLE
Mistakes latest version of the onedrive client version as not being compatible/up to date

### ISSUE THREAD

**Issue by c3101** [bpozdena/OneDriveGUI#182]
Reports the version to be "unsupported" and says it needs to be upgraded.
Refuses to start the sync process.

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/abraunegg/onedrive/releases/latest HTTP/1.1" 200 3236
DEBUG:root:[GUI] Client version check: {'latest_client_version': 'v2.5.0', 'installed_client_version': 'v2.5.0'}
DEBUG:root:[FNB] Compatible client version found: False

**Comment by EpicPilgrim** [comment]
![image](https://github.com/user-attachments/assets/3cded077-8a8c-486d-a795-bc56a13234ce)

+1

**Comment by EpicPilgrim** [comment]
Update: Downloaded the 1.1.0 AppImage and now I get this when loading OneDriveGUI:

![image](https://github.com/user-attachments/assets/f158debc-dd78-4c01-b082-3ba6125545bf)

Clicking the link takes me to a page that says NOTHING about the deprecation. Considering the only reason I use onedrive/OneDriveGUI is to sync business folders, this is a tad frustrating.

**Comment by abraunegg** [comment]
@EpicPilgrim , @c3101 , @MightyMirko

If running v2.5.0 client at the back end , you *must* upgrade your GUI client ... this information is really clear.

@EpicPilgrim 

Business Shared Folder support has been *totally* overhauled. Please read:
* https://github.com/abraunegg/onedrive/releases
* https://github.com/abraunegg/onedrive/blob/master/docs/business-shared-items.md

You *MUST* first take remediation action on your system and/or online.

**Comment by EpicPilgrim** [comment]
Thanks @abraunegg . Not sure this is necessarily the best place to ask this, but I am having trouble getting my shared folder to sync with this new setup. Below is my config:

```
sync_dir = "/home/user/Documents/OneDrive"
enable_logging = "true"
sync_business_shared_items = "true"
```

Below is my sync_list file:

```
Documents - Client - ABC/*
```
_(note that if I use "/Documents - Client - ABC/", it skips the folder entirely. Only seems to work if I drop the leading "/")_

Here is the command I'm running:

```
$ onedrive --confdir=/home/user/.config/onedrive/accounts/OneDrive --monitor -v --resync
```

Here is the relevant bit of the output:

```
Syncing this OneDrive Business Shared Folder: Documents - Client - ABC
Generating a /delta response from the OneDrive API for Drive ID: b!NyrLTpXxxxxu4j3GjGvFtvkB0bld1HZAssYrbxxxxaO6kwGSr_E2QoNyFGU0_TW9
Adding OneDrive folder details for processing
Adding 20 OneDrive items for processing from the OneDrive Shared Folder
Skipping path - excluded by sync_list config: AI Policy
Skipping path - excluded by sync_list config: Applications
Skipping path - excluded by sync_list config: Contracts
Skipping path - excluded by sync_list config: Cybersecurity
Skipping path - excluded by sync_list config: General
Skipping path - excluded by sync_list config: Insurance
Skipping path - excluded by sync_list config: Meetings
Skipping path - excluded by sync_list config: Members
Skipping path - excluded by sync_list config: Pre-Engagement
Skipping path - excluded by sync_list config: Previous ICT Review
Skipping path - excluded by sync_list config: Risk management
Skipping path - excluded by sync_list config: Staff policies
Finished processing self generated /delta JSON response from the OneDrive API
```

What am I missing as to why it is skipping the contents of the OneDrive Shared Folder in sync_list?

**Comment by abraunegg** [comment]
Wrong place to seek support. Please follow the correct process

**Comment by bpozdena** [comment]
> Reports the version to be "unsupported" and says it needs to be upgraded. Refuses to start the sync process.
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443 DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/abraunegg/onedrive/releases/latest HTTP/1.1" 200 3236 DEBUG:root:[GUI] Client version check: {'latest_client_version': 'v2.5.0', 'installed_client_version': 'v2.5.0'} DEBUG:root:[FNB] Compatible client version found: False

This seems like a legitimate issue, but I can't assist you because, for some reason, you deleted all the questions from the issue template and didn't provide enough details for me to reproduce it. Please include all the requested information if you require assistance.

**Comment by EpicPilgrim** [comment]
> Please help me understand how else to communicate this information to users such as yourself.

I guess you've hit the nail on the head. I'm a business user with a technical background. I don't read the readme files of the dozens of packages I update weekly with the push of a button. They just break and then I spend the rest of the day figuring out how to fix them. Nobody's fault, it's life as a Linux user.

It would appear the OneDrive package was updated in the Ubuntu repo I use today. That is the root cause of OneDriveGUI then breaking and then me going on a path of self-discovery to figure out what relies on what and how to reconfigure it all to start working again.

**Comment by bpozdena** [comment]
> > Please help me understand how else to communicate this information to users such as yourself.
> 
> I guess you've hit the nail on the head. I'm a business user with a technical background. I don't read the readme files of the dozens of packages I update weekly with the push of a button. They just break and then I spend the rest of the day figuring out how to fix them. Nobody's fault, it's life as a Linux user.

That's fair. Do you have any suggestion you think would have helped you better understand what you need to do to fix the issue? [For example change the wording in the documentation in a specific way or show different message on GUI startup, etc. ]

**Comment by EpicPilgrim** [comment]
> That's fair. Do you have any suggestion you think would have helped you better understand what you need to do to fix the issue? [For example change the wording in the documentation in a specific way or show different message on GUI startup, etc. ]

The problem here might be the chicken before the egg. The version of OneDriveGUI I was running wouldn't have known about 2.5.0 coming out, so having your code prepped in advance for new versions with relevant info may be difficult. However, in this case, it told me to upgrade the OneDrive application. In fact, what I needed to do was start by updating OneDriveGUI, and then the pieces started falling into place.

As a lay-developer (once upon a time), potentially there could be a "compatibility check" on startup against a file in GitHub or something, that allows you to insert custom, helpful error messages on load if a version mismatch occurs? Probably a hundred reasons this is a bad idea, but it would work around you having to preempt every possible problem with version mismatches in code.

**Comment by bpozdena** [comment]
> potentially there could be a "compatibility check" on startup against a file in GitHub or something, that allows you to insert custom, helpful error messages on load if a version mismatch occurs? 

The compatibility check is in place, and it seems to have worked based on your first screenshot. If you hover your mouse over the yellow triangle, it would show the version mismatch.

I’m considering displaying a pop-up message with more detailed information directly in the GUI, so there would be no need to open the documentation on GitHub. However, I would also need to redesign the GUI to accommodate longer text messages, but this would require a complete overhaul, which I don’t have time for at the moment.

**Comment by marty-macfly** [comment]
I've report an issue with version detection issue when I'm building from source base on tag v1.1.0, it doesn't detect onedrive version 2.5.0 properly, I've tried with version in main that as a fix about version detection and it works properly so I think there is may be an issue for the tag, sorry for the double post https://github.com/bpozdena/OneDriveGUI/issues/181#issuecomment-2369207055 . I'm trying to avoid creating an issue if it already exist.

**Comment by TxLysy** [comment]
I updated onedrive-abraunegg 2.5.0-1 and onedrivegui-git 1.1.0rc1.r13.g0dff571-1 with yay command in archlinux 6.10.10 and encountered the same issue, and I think I find something useful. 

I deleted the line [sync_business_shared_folders = "true|false"] from config of Onedrive following the document [business-shared-items.md](https://github.com/abraunegg/onedrive/blob/master/docs/business-shared-items.md) and pressed the button to restart the sync and it didn't work. After restarting once more, the error [Business Shared Folder...] appeared again, and the line deleted appeared again in config. 

Finally, I found that the OneDrive client binary path in the setting gui of OneDriveGUI was not correct when following the steps in readme of Onedrive-GUI. It did work after I fixed the path, and the config of OneDrive never recovered any more. So the perspective of @marty-macfly may be right, OneDrive-GUI can not recognize OneDrive with wrong path (maybe something wrong changes the path in the new version), and probably it recovers the config of OneDrive according to the config in old version (eg. 2.4.x), which results in the sustain error[Business Shared Folder...]. 

The yellow triangle will appear if you use onedrivegui v1.1.0 rather than the one yay updated and maybe there is something wrong in the version management.

**Comment by Staudey** [comment]
I had to apply commit https://github.com/bpozdena/OneDriveGUI/commit/2ef98dc7a501857a857e9507ea15d1f0c4ef5720 to get the version check to work correctly. For some reason this doesn't seem to be part of the 1.1.0 release

**Comment by bjornmp** [comment]
In release v1.1.0 the .AppImage is from last week.

The source code v1.1.0.tar.gz however is from **May 7**.

The .tar.gz is the one Arch AUR packages are pulling for the build and it seems to be outdated.

**Comment by bpozdena** [comment]
I originally deleted the release due to minor issue. But it looks like Github re-uses old code when release tag is reused. 

To fix the AUR issues, I adjusted the code in GUI v1.1.1 based on AUR PKGBUILD of `onedrivegui-git` . 

I've just tested the AUR package `onedrivegui-git` and it works as expected.
