### ISSUE TITLE
Show warning when onedrive client is not installed

### ISSUE THREAD

**Issue by bpozdena** [bpozdena/OneDriveGUI#27]
Show warning when onedrive client is not installed but pre-existing OneDriveGUI profile was detected.

**Comment by abraunegg** [comment]
@bpozdena 
An expansion here would be also if the client version is not correct - for example the 'skilion' code base.

Folk using Arch AUR - if they install 'onedrive' rather than 'onedrive-abraunegg' - same binary but the 'skilion' code will be v1.1.4 - so if that is installed, and the GUI is installed, a lot of the additional options / configuration etc is not going to work or be compatible.

**Comment by bpozdena** [comment]
Client version check is now enforced. Minimum supported client version is currently 2.4.15.
 
If OneDrive client is not installed or is older than minimum supported version, the bellow actions will take place:
-setup wizard will not work
-Start sync button will be grayed out
-Settings button will be grayed out
