### ISSUE TITLE
Tray Icon not shown under Gnome 42.2 (Manjaro)

### ISSUE THREAD

**Issue by SvenAbels** [bpozdena/OneDriveGUI#41]
I installed the AUR version onedrivegui-git (0.2.0.r0.g1cb36f..) and it works well but the tray icon is not displayed under Gnome 42.2 (Manjaro, Wayland).  If I use the AppImage, then it is displayed. 

Does anyone have an idea why this might happen? 

(Also, when I swelect tzhe option to launch as a minimized window, then I cannot access the window at all but I assume that this is because only the tray icon is loaded, which is not displayed as described above. )

Best regards,

Sven

**Comment by bpozdena** [comment]
I just tested the AUR package on Manjaro Gnome 42.3 and the tray icon worked as expected. Though the VM came with just X11 installed. I tried to install Wayland manually but I only got a black screen... 

Maybe you can try switching to X11 and see if it works there.. at least as a test. 

Also please try to run the GUI from CLI by executing 'onedrivegui' command and see if there are any errors in the console output.

**Comment by SvenAbels** [comment]
OK, In see. What is strange is that the icon appears for me if I use the AppImage Version

**Comment by SvenAbels** [comment]
As an update: I've tested it with X11 now and the tray icon works fine - even when using the Gnome 42.3 layout where the tray icon is at the top. As soon as I nswitch to Wayland, the icon is not showing anymore.

**Comment by bpozdena** [comment]
Thanks for the update - hopefully you can keep running X11 for the moment.

As far as I know the Tray menu is not supported at all in vanilla Gnome 42 and requires extensions that seem to break after each Gnome update. Considering how many Gnome related issues there are with the tray icons and their context menus, I will probably have to implement Minimize To Taskbar feature and different menu.

**Comment by bpozdena** [comment]
I think I may have found a decent solution. Please try [OneDriveGUI-0.2.2-fix41-x86_64.AppImage](https://github.com/bpozdena/OneDriveGUI/releases/download/v0.2.2/OneDriveGUI-0.2.2-fix41-x86_64.AppImage)  and let me know if there are any further issues. 

The expected behavior is that OneDriveGUI will minimize to tray only when it is available, otherwise it will minimize to dock/taskbar. 

I've tested successfully with:
- X11/Wayland
- KDE/Cinnamon/Gnome
- Fedora with vanilla Gnome, 
- Fedora with Gnome + Tray Icons Reloaded extension
- All Manjaro Gnome layouts (only Traditional one has system tray)
- Start Minimized option enabled/disabled

**Comment by SvenAbels** [comment]
Great! 

This works perfectly fine and the is now shown correctly for me under Gnome 42.2 (Manjaro, Wayland). :-)

Thanks a lot. :-)

**Comment by bpozdena** [comment]
Awesome! Thank you too ! Let's see how long it takes before it breaks again in next Gnome release :D
