### ISSUE TITLE
v1.0. RC1 Need to show warning if onedrive is already running when starting the GUI

### ISSUE THREAD

**Issue by rogercreagh** [bpozdena/OneDriveGUI#55]
By default onedrive runs automatically in monitor mode on system login. When the GUI starts it doesn't detect that onedrive is already running and reports "Onedrive is sync not running" (which is also bad English - should be "Onedrive sync is not running") which of course is not true.
If you press the play button it hangs with the message Initializing the Onedrive API"
In the log you find the following lines:
```
2022-08-22 22:32:24,479 [OneDriveGUI.py:1995][fn=run][INFO] - [Roger] Opening the item database ...
2022-08-22 22:32:24,479 [OneDriveGUI.py:1995][fn=run][INFO] - [Roger] - Use 'sudo ps aufxw | grep onedrive' to potentially determine acive running process
2022-08-22 22:32:24,479 [OneDriveGUI.py:1995][fn=run][INFO] - [Roger] 
2022-08-22 22:32:24,753 [OneDriveGUI.py:2130][fn=run][INFO] - @ERROR 
```
So it looks like it is detecting that onedrive is already running when you manually try to start it from the GUI.
Shouldn't it also run this check when the GUI is initialised so it can report that onedrive --monitor is running?

**Comment by bpozdena** [comment]
Thanks for reporting the issues @rogercreagh .  

The GUI will now handle this situation more gracefully. It will automatically stop the failed worker and show the bellow status message.
![image](https://user-images.githubusercontent.com/24818591/186228484-1fe35a6b-9704-46d3-ba90-dd25eed7c49a.png)


Just note that this message will only appear after you attempt to start sync from the GUI manually or after GUI startup if you have auto-sync enabled. I do not plan to monitor or manage processes which were started outside the GUI scope. 


I had to remove RC1 due to another critical issue I discovered. Feel free to test updated [v1.0.0-RC2 AppImage](https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.0.0-RC2 )  .

**Comment by rogercreagh** [comment]
This is a good fix to the immediate bug of it hanging if another instance of onedrive is running but it leaves the underlying problem.
The onedrive app somehow makes itself automatically run in monitor mode on system start - which means you have to find the process and kill it before you can run onedrive.
I have been unable to find how onedrive is autorunning on boot - it doesn't seem to be in any of the obvious places so I can't change this behaviour which is a pain. That makes OneDriveGUI pretty unusable for simple use.
Since you can detect it is already running (as it usually will be by default) could you not provide a button to kill the exiting process?
Alternatively perhaps you need to bundle a non-autorunning version of onedrive client with the GUI and advise the need to uninstall the existing client and add the GUI to the Startup Applications list if you want onedrive to always be running (which seems normal to me)

**Comment by bpozdena** [comment]
Depending on how you have installed OneDrive client, you should be able to stop the systemd service with `systemctl --user stop onedrive` or `systemctl stop onedrive@<username>.service`. 

To prevent OneDrive client from starting on startup, you should be able to disable the systemd service with `systemctl --user disable onedrive` or `systemctl disable onedrive@<username>.service` . 

You can check the official documentation at https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#running-onedrive-as-a-system-service
