### ISSUE TITLE
Feature request: Create webhooks automically

### ISSUE THREAD

**Issue by panther7** [bpozdena/OneDriveGUI#78]
Is it posibble, create local webhook "server"?

**Comment by bpozdena** [comment]
I'm not sure I understand your query/requirements or how it relates to this GUI project.

The GUI already supports webhook configuration:
![image](https://user-images.githubusercontent.com/24818591/215481986-8bd19382-c345-477f-8864-57acbc6d3552.png)

More details can be found in the [OneDrive client](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#use-webhook-to-subscribe-to-remote-updates-in-monitor-mode) documentation. Since it is a different project, please ask there if you have any questions/requests specific to the OneDrive client.
