### ISSUE TITLE
Light icon in dark mode (Zorin OS)

### ISSUE THREAD

**Issue by panther7** [bpozdena/OneDriveGUI#83]
dark mode:
![image](https://user-images.githubusercontent.com/3808250/218308070-331d5e93-2c41-4b6f-bfdf-62b10671d255.png)

light mode:
![image](https://user-images.githubusercontent.com/3808250/218308084-1f4d2919-35e1-4973-975e-72afb3bffddd.png)

OS: [Zorin OS 16.2](https://zorin.com/os/)
OneDriveGUI: 1.0.1_82

**Comment by bpozdena** [comment]
@panther7 , zkusil jsem to, ale neporarilo se mi to udelat tak aby to fungovalo na vsech distribucich...

I really tried, but it turned out to be too much work to make work reliably on Plasma/Gnome/DashToDock/XFCE/Zorin/Cinnamon... with all possible task bar colors.

So, I just put a high contrast border around the icon. I can't spend more time on it. 

Zorin:
![image](https://user-images.githubusercontent.com/24818591/218334634-2e1b25ae-e7af-406d-b6a7-ead12d2bb576.png)
![image](https://user-images.githubusercontent.com/24818591/218334663-a2997bd4-85ce-456e-8b43-7d6b6d7912a1.png)


Plasma:
![image](https://user-images.githubusercontent.com/24818591/218334595-0496be6a-f450-4b5b-9861-337700eb2a74.png)
![image](https://user-images.githubusercontent.com/24818591/218334611-526bbb8f-8217-4f09-92d5-d3bea53d750a.png)


Dash to Dock:
![image](https://user-images.githubusercontent.com/24818591/218334382-a99f971b-9b4e-4732-b84f-5d224e7b1fbd.png)
![image](https://user-images.githubusercontent.com/24818591/218334453-dadf4aa5-bb9a-4cf9-90f1-e89ee659ae63.png)
![image](https://user-images.githubusercontent.com/24818591/218334521-7a23cb31-911a-4b5b-8a7c-1fbc29e61c0b.png)

Cinnamon:
![image](https://user-images.githubusercontent.com/24818591/218334709-bb66da7b-5a80-4ac7-bde6-cf2e209f153c.png)
![image](https://user-images.githubusercontent.com/24818591/218334759-d3430e66-b1b3-4ded-aad9-a0b5e642794c.png)
